import { Category, DeliverySlot, Product, Seller } from './types.js';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-sweets',
    name: 'Sweets',
    slug: 'sweets',
    description: 'Authentic Uttar Pradesh traditional sweets made with pure ghee and mawa.',
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-namkeen',
    name: 'Namkeen',
    slug: 'namkeen',
    description: 'Crispy, spiced savory snacks traditionally prepared during festivals.',
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-festival',
    name: 'Festival Specials',
    slug: 'festival-specials',
    description: 'Holi, Diwali, Chhath and Teej special festive delicacies available on pre-order.',
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-regional',
    name: 'Regional Specialties',
    slug: 'regional-specialties',
    description: 'Kanpur, Lucknow, Varanasi, and Gorakhpur heritage food items.',
    createdAt: new Date('2026-01-01').toISOString(),
  },
];

export const INITIAL_SELLERS: Seller[] = [
  {
    id: 'seller-shukla',
    name: 'Shukla Mishthan & Halwai Heritage',
    contactPerson: 'Rameshwar Shukla',
    phone: '6397353920',
    city: 'Kanpur',
    area: 'Birhana Road',
    fssaiNumber: '12722001000452',
    verificationStatus: 'VERIFIED',
    status: 'ACTIVE',
    notes: 'Specializes in traditional Gujiya and pure desi ghee mathri batches.',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'seller-awadh',
    name: 'Awadh Heritage Sweet Crafters',
    contactPerson: 'Suresh Chandra Gupta',
    phone: '9415098765',
    city: 'Lucknow',
    area: 'Aminabad',
    fssaiNumber: '12723002000891',
    verificationStatus: 'VERIFIED',
    status: 'ACTIVE',
    notes: 'Famous for flaky Balushahi and Besan Laddoo.',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'seller-banaras',
    name: 'Kashi Rasoi & Halwai Collective',
    contactPerson: 'Deepak Upadhyay',
    phone: '9792044321',
    city: 'Varanasi',
    area: 'Godowlia',
    fssaiNumber: '12724003001123',
    verificationStatus: 'VERIFIED',
    status: 'ACTIVE',
    notes: 'Masters of Thekua, Lal Peda, and festive Namak Para.',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-gujiya',
    name: 'Traditional Mawa Gujiya',
    slug: 'traditional-gujiya-kanpur',
    description: 'Crisp, flaky pastry shells stuffed with rich slow-cooked Khoya/Mawa, crushed green cardamom, grated dry coconut, and premium dry fruits (cashews, almonds, chironji). Deep-fried in pure desi ghee to golden perfection.',
    categoryId: 'cat-sweets',
    price: 349,
    unit: '500g',
    weight: '500g (~12-14 pcs)',
    approxPieces: '12-14 pcs',
    imageUrl: '/images/products/mawa-gujiya.jpg',
    ingredients: 'Mawa (Khoya), Refined Wheat Flour (Maida), Pure Desi Ghee, Sugar, Cashew nuts, Almonds, Chironji, Cardamom powder.',
    allergens: 'Contains Dairy (Milk/Khoya/Ghee), Gluten, and Tree Nuts.',
    shelfLife: '10 days at room temperature, 20 days refrigerated.',
    storageInstructions: 'Store in an airtight container in a cool, dry place away from direct sunlight.',
    status: 'ACTIVE',
    availableQuantity: 45,
    preOrderDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Upcoming Friday & Saturday batches',
    city: 'Kanpur',
    createdAt: new Date('2026-01-05').toISOString(),
    updatedAt: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-mathri',
    name: 'Halwai-Style Khasta Mathri',
    slug: 'halwai-style-mathri',
    description: 'Classic Uttar Pradesh spiced savory flaky crackers with whole black peppercorns (kali mirch), ajwain (carom seeds), and kasuri methi. Layered dough fried on low flame for exceptional crunch.',
    categoryId: 'cat-namkeen',
    price: 199,
    unit: '500g',
    weight: '500g (~18-20 pcs)',
    approxPieces: '18-20 pcs',
    imageUrl: '/images/products/khasta-mathri.jpg',
    ingredients: 'Refined Wheat Flour, Ajwain (Carom seeds), Black Pepper, Kasuri Methi, Desi Ghee shortening, Rock Salt, Groundnut Oil.',
    allergens: 'Contains Gluten.',
    shelfLife: '45 days in an airtight container.',
    storageInstructions: 'Keep in a dry container. Do not expose to moisture or humid air.',
    status: 'ACTIVE',
    availableQuantity: 60,
    preOrderDeadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Next Batch Available',
    city: 'Kanpur',
    createdAt: new Date('2026-01-05').toISOString(),
    updatedAt: new Date('2026-01-05').toISOString(),
  },
  {
    id: 'prod-namak-para',
    name: 'Crispy Ajwain Namak Para',
    slug: 'crispy-namak-para',
    description: 'Diamond-cut golden salted snack ribbons infused with roasted ajwain and rock salt. An essential companion for evening chai and festival gatherings.',
    categoryId: 'cat-namkeen',
    price: 179,
    unit: '500g',
    weight: '500g',
    approxPieces: null,
    imageUrl: '/images/products/crispy-namakpara.jpg',
    ingredients: 'Wheat Flour, Semolina (Sooji), Ajwain, Black Salt, Pure Groundnut Oil, Cumin.',
    allergens: 'Contains Gluten.',
    shelfLife: '40 days in airtight container.',
    storageInstructions: 'Store in cool dry conditions.',
    status: 'ACTIVE',
    availableQuantity: 50,
    preOrderDeadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Fresh Batch Weekly',
    city: 'Kanpur',
    createdAt: new Date('2026-01-06').toISOString(),
    updatedAt: new Date('2026-01-06').toISOString(),
  },
  {
    id: 'prod-shakar-para',
    name: 'Sweet Crunchy Shakar Para',
    slug: 'sweet-shakar-para',
    description: 'Crispy diamond-shaped pastry gems coated with a delicate, crunchy sugar glaze. Perfectly balanced sweetness with a hint of green cardamom.',
    categoryId: 'cat-sweets',
    price: 189,
    unit: '500g',
    weight: '500g',
    approxPieces: null,
    imageUrl: '/images/products/sweet-shakarpara.jpg',
    ingredients: 'Refined Wheat Flour, Sugar, Pure Desi Ghee, Cardamom, Pure Filtered Water.',
    allergens: 'Contains Gluten and Dairy.',
    shelfLife: '30 days in sealed container.',
    storageInstructions: 'Store at room temperature in an airtight jar.',
    status: 'ACTIVE',
    availableQuantity: 40,
    preOrderDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Weekly Batch',
    city: 'Lucknow',
    createdAt: new Date('2026-01-06').toISOString(),
    updatedAt: new Date('2026-01-06').toISOString(),
  },
  {
    id: 'prod-thekua',
    name: 'Purvanchal Gur Thekua',
    slug: 'traditional-gur-thekua',
    description: 'Traditional Eastern UP and Bihar festive prasad snack. Made with stone-ground whole wheat flour, organic sugarcane jaggery (gur), dry coconut shreds, and aromatic fennel seeds (saunf), pressed on wooden sancha molds.',
    categoryId: 'cat-festival',
    price: 249,
    unit: '500g',
    weight: '500g (~15 pcs)',
    approxPieces: '14-16 pcs',
    imageUrl: '/images/products/purvanchal-thekua.jpg',
    ingredients: 'Whole Wheat Flour (Atta), Organic Desi Gur (Jaggery), Desi Ghee, Dry Coconut (Gari), Fennel Seeds (Saunf), Green Cardamom.',
    allergens: 'Contains Gluten and Dairy.',
    shelfLife: '25 days at room temperature.',
    storageInstructions: 'Store in dry airtight tin container.',
    status: 'ACTIVE',
    availableQuantity: 35,
    preOrderDeadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Bi-Weekly Fresh Batch',
    city: 'Varanasi',
    createdAt: new Date('2026-01-07').toISOString(),
    updatedAt: new Date('2026-01-07').toISOString(),
  },
  {
    id: 'prod-besan-laddoo',
    name: 'Shuddh Desi Ghee Besan Laddoo',
    slug: 'shuddh-ghee-besan-laddoo',
    description: 'Coarse gram flour (Danedar Besan) slow-roasted in pure cow desi ghee for over an hour until fragrant and golden, blended with boora sugar, toasted melon seeds (magaz), and crushed green cardamom.',
    categoryId: 'cat-sweets',
    price: 320,
    unit: '500g',
    weight: '500g (10-12 laddoos)',
    approxPieces: '10-12 pcs',
    imageUrl: '/images/products/besan-laddoo.jpg',
    ingredients: 'Coarse Gram Flour (Danedar Besan), Pure Cow Desi Ghee, Tagar/Boora Sugar, Cardamom, Muskmelon Seeds (Magaz), Pistachio slivers.',
    allergens: 'Contains Dairy and Nuts (Pistachio, Melon seeds).',
    shelfLife: '20 days at room temperature.',
    storageInstructions: 'Store in a cool dry container.',
    status: 'ACTIVE',
    availableQuantity: 30,
    preOrderDeadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Freshly Prepared on Demand',
    city: 'Lucknow',
    createdAt: new Date('2026-01-08').toISOString(),
    updatedAt: new Date('2026-01-08').toISOString(),
  },
  {
    id: 'prod-balushahi',
    name: 'Awadhi Shahi Balushahi',
    slug: 'awadhi-balushahi',
    description: 'Flaky, layered mawa pastry fried gently on slow flame and steeped in aromatic saffron and rose infused sugar syrup. Crisp outer texture with a luscious, juicy interior.',
    categoryId: 'cat-regional',
    price: 299,
    unit: '500g',
    weight: '500g (8-10 pcs)',
    approxPieces: '8-10 pcs',
    imageUrl: '/images/products/awadhi-balushahi.jpg',
    ingredients: 'Refined Flour, Pure Desi Ghee, Sugar, Saffron (Kesar), Kewra water, Cardamom, Pistachio garnish.',
    allergens: 'Contains Gluten, Dairy, and Nuts.',
    shelfLife: '7 days at room temperature, 14 days refrigerated.',
    storageInstructions: 'Store in a sealed box in a cool room.',
    status: 'ACTIVE',
    availableQuantity: 25,
    preOrderDeadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Weekend Delivery Batch',
    city: 'Lucknow',
    createdAt: new Date('2026-01-08').toISOString(),
    updatedAt: new Date('2026-01-08').toISOString(),
  },
  {
    id: 'prod-kachori',
    name: 'Spiced Khasta Moong Dal Kachori',
    slug: 'khasta-moong-dal-kachori',
    description: 'Ultra-crispy puffed pastry stuffed with coarsely ground yellow moong dal spiced with saunf, hing (asafoetida), amchur, and garam masala. The authentic halwai festive favorite.',
    categoryId: 'cat-namkeen',
    price: 199,
    unit: '500g',
    weight: '500g (8 pcs)',
    approxPieces: '8 pcs',
    imageUrl: '/images/products/khasta-kachori.jpg',
    ingredients: 'Refined Wheat Flour, Yellow Moong Dal, Asafoetida (Hing), Fennel Seeds, Dried Mango Powder (Amchur), Coriander Powder, Red Chilli, Pure Groundnut Oil, Rock Salt.',
    allergens: 'Contains Gluten.',
    shelfLife: '12 days in an airtight container.',
    storageInstructions: 'Store in an airtight container. Can be lightly warmed in an oven/tawa before serving.',
    status: 'ACTIVE',
    availableQuantity: 40,
    preOrderDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryDates: 'Fresh Batch Every Saturday',
    city: 'Kanpur',
    createdAt: new Date('2026-01-09').toISOString(),
    updatedAt: new Date('2026-01-09').toISOString(),
  },
];

export const INITIAL_DELIVERY_SLOTS: DeliverySlot[] = [
  {
    id: 'slot-1',
    city: 'Kanpur',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '10:00 AM',
    endTime: '02:00 PM',
    pincodes: '208001,208002,208005,208012,208024,208027',
    capacity: 50,
    reservedCapacity: 4,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'slot-2',
    city: 'Kanpur',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '03:00 PM',
    endTime: '07:00 PM',
    pincodes: '208001,208002,208005,208012,208024,208027',
    capacity: 50,
    reservedCapacity: 2,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'slot-3',
    city: 'Lucknow',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '11:00 AM',
    endTime: '03:00 PM',
    pincodes: '226001,226002,226010,226016,226024',
    capacity: 40,
    reservedCapacity: 3,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'slot-4',
    city: 'Varanasi',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '10:00 AM',
    endTime: '02:00 PM',
    pincodes: '221001,221002,221005,221010',
    capacity: 35,
    reservedCapacity: 1,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
];
